potcoind enhancements:  * commit based versioned ebuild  * better init-script inspired by dashd

diff --git a/net-p2p/potcoind/files/potcoin.initd b/net-p2p/potcoind/files/potcoin.initd
--- a/net-p2p/potcoind/files/potcoin.initd
+++ b/net-p2p/potcoind/files/potcoin.initd
@@ -3,27 +3,81 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
 
-vardir="/var/lib/potcoin"
-conffile="${vardir}/.potcoin/potcoin.conf"
-potcoind_user="${POTCOIN_USER:-nobody:nobody}"
+# backward compatibility for existing gentoo layout
+#
+if [ -d "/var/lib/potcoin/.potcoin" ]; then
+	BITCOIND_DEFAULT_DATADIR="/var/lib/potcoin/.potcoin"
+else
+	BITCOIND_DEFAULT_DATADIR="/var/lib/potcoind"
+fi
 
-description="A lite version of Bitcoin using scrypt as a proof-of-work algorithm."
-pidfile="/run/${SVCNAME}.pid"
-command="/usr/bin/potcoind"
-command_args="${POTCOIN_OPTS}"
-command_background="true"
-start_stop_daemon_args="-u ${potcoind_user} -e HOME=${vardir} -N ${NICELEVEL:-0} -w 2000"
+BITCOIND_CONFIGFILE=${BITCOIND_CONFIGFILE:-/etc/potcoin/potcoin.conf}
+BITCOIND_PIDDIR=${BITCOIND_PIDDIR:-/var/run/potcoind}
+BITCOIND_PIDFILE=${BITCOIND_PIDFILE:-${BITCOIND_PIDDIR}/${SVCNAME}.pid}
+BITCOIND_DATADIR=${BITCOIND_DATADIR:-${BITCOIND_DEFAULT_DATADIR}}
+BITCOIND_USER=${BITCOIND_USER:-potcoin}
+BITCOIND_GROUP=${BITCOIND_GROUP:-potcoin}
+BITCOIND_BIN=${BITCOIND_BIN:-/usr/bin/potcoind}
+
+name="Potcoin Core Daemon"
+description="Potcoin crypto-currency p2p network daemon"
+
+command="${BITCOIND_BIN}"
+command_args="-pid=\"${BITCOIND_PIDFILE}\" \
+		-conf=\"${BITCOIND_CONFIGFILE}\" \
+		-datadir=\"${BITCOIND_DATADIR}\" \
+		-daemon \
+		${BITCOIND_OPTS}"
+required_files="${BITCOIND_CONFIGFILE}"
+start_stop_daemon_args="-u ${BITCOIND_USER} -e HOME=${BITCOIND_DATADIR} \
+                        -N ${BITCOIND_NICE:-19} -w 2000"
+pidfile="${BITCOIND_PIDFILE}"
+retry=60
 
 depend() {
-	need net
+	need localmount net
 }
 
 start_pre() {
-	checkpath -f -o ${potcoind_user} -m 0400 ${conffile} || return 1
+	checkpath \
+	-d \
+	--mode 0750 \
+	--owner "${BITCOIND_USER}:${BITCOIND_GROUP}" \
+	"${BITCOIND_DATADIR}"
 
-	if ! grep -q '^rpcpassword=' "${conffile}"; then
-		eerror "Please edit `readlink -f ${conffile}`"
-		eerror "There must be at least a line assigning rpcpassword=something-secure"
+	checkpath \
+	-d \
+	--mode 0755 \
+	--owner "${BITCOIND_USER}:${BITCOIND_GROUP}" \
+	"${BITCOIND_PIDDIR}"
+
+	checkpath -f \
+	-o ${BITCOIND_USER}:${BITCOIND_GROUP} \
+	-m 0660 \
+	${BITCOIND_CONFIGFILE}
+
+	checkconfig || return 1
+}
+
+checkconfig() {
+	if ! grep -qs '^rpcpassword=' "${BITCOIND_CONFIGFILE}" ; then
+		eerror ""
+		eerror "ERROR: You must set a secure rpcpassword to run potcoind."
+		eerror "The setting must appear in ${BITCOIND_CONFIGFILE}"
+		eerror ""
+		eerror "This password is security critical to securing wallets "
+		eerror "and must not be the same as the rpcuser setting."
+		eerror "You can generate a suitable random password using the following"
+		eerror "command from the shell:"
+		eerror ""
+		eerror "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
+		eerror ""
+		eerror "It is also recommended that you also set alertnotify so you are "
+		eerror "notified of problems:"
+		eerror ""
+		eerror "ie: alertnotify=echo %%s | mail -s \"Potcoin Alert\"" \
+			"admin@foo.com"
+		eerror ""
 		return 1
 	fi
 }
